export interface Order{
	address:string | null;
	amount_paid:number;
	ares:number | null;
	authorized_by:string | null;
	billing_address_id:number | null;
	billing_data_id:number | null;
	cancellation_reason:string | null;
	cancellation_timestamp:Date | null;
	cancelled_by_user_id:number | null;
	cashier_user_id:number | null;
	city:string | null;
	client_name:string | null;
	client_user_id:number | null;
	closed_timestamp:Date | null;
	created:Date;
	currency_id:string;
	delivery_status:'PENDING'|'SENT'|'DELIVERED'|'CANCELLED'|'READY_TO_PICKUP';
	delivery_user_id:number | null;
	discount:number;
	discount_calculated:number;
	facturacion_code:string;
	facturado:'NO'|'YES';
	guests:number | null;
	id:number;
	lat:number | null;
	lng:number | null;
	initial_payment:number;
	marked_for_billing:'YES'|'NO';
	note:string | null;
	paid_status:'PENDING'|'PAID'|'PARTIALLY_PAID';
	paid_timetamp:Date | null;
	period_id:number | null;
	price_type_id:number
	quote_id:number | null;
	sat_codigo_postal:string | null;
	sat_domicilio_fiscal_receptor:string | null;
	sat_factura_id:number | null;
	sat_forma_pago:string | null;
	sat_ieps:number;
	sat_isr:number;
	sat_exchange_rate:number;
	sat_pdf_attachment_id:number | null;
	sat_razon_social:string | null;
	sat_receptor_email:string | null;
	sat_receptor_rfc:string | null;
	sat_regimen_capital_receptor:string | null;
	sat_regimen_fiscal_receptor:string | null;
	sat_serie:string | null;
	sat_serie_consecutive:number | null;
	sat_uso_cfdi:string | null;
	sat_xml_attachment_id:number | null;
	service_type:'TOGO'|'IN_PLACE'|'PICK_UP'|'QUICK_SALE';
	shipping_address_id:number | null;
	shipping_cost:number;
	state:string | null;
	status:'PENDING'|'CANCELLED'|'ACTIVE'|'CLOSED';
	store_consecutive:number | null;
	store_id:number
	subtotal:number;
	suburb:string | null;
	sync_id:string | null;
	system_activated:Date | null;
	table_id:number | null;
	tag:string | null;
	tax:number;
	tax_percent:number;
	total:number;
	updated:Date;
	version_created:string | null;
	version_updated:string | null;
}
